// Generated by https://quicktype.io

export interface DataCards {
  id:          number;
  name:        string;
  type:        string;
  frameType:   string;
  desc:        string;
  atk:         number;
  def:         number;
  level:       number;
  race:        string;
  attribute:   string;
  archetype:   string;
  card_sets:   CardSet[];
  card_images: CardImage[];
  misc_info:   MiscInfo[];
}

export interface CardImage {
  id:                number;
  image_url:         string;
  image_url_small:   string;
  image_url_cropped: string;
}

export interface CardSet {
  set_name:        string;
  set_code:        string;
  set_rarity:      string;
  set_rarity_code: string;
  set_price:       string;
}

export interface MiscInfo {
  formats:    string[];
  tcg_date:   string;
}
